name: ArXiv Paper Notifications

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-paper:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to write to the JSONL file
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sentence-transformers arxiv numpy scikit-learn python-dotenv srsly
          
      - name: Find and send paper
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_LIST: ${{ secrets.RECIPIENT_LIST }}
        run: |
          python arxiv_emailer.py
          
      - name: Commit and push if history changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/potd.jsonl
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update paper history" && git push)
